# Generated by Django 5.1.7 on 2025-03-18 05:03

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('risks', 'Category')
    # Create default categories
    categories = [
        {'name': 'Technical', 'description': 'Risks related to technology, infrastructure, or technical implementation.'},
        {'name': 'Financial', 'description': 'Risks related to budget, costs, funding, or financial resources.'},
        {'name': 'Operational', 'description': 'Risks related to operations, processes, or day-to-day activities.'},
        {'name': 'Legal', 'description': 'Risks related to legal issues, regulations, compliance, or contracts.'},
        {'name': 'Strategic', 'description': 'Risks related to business strategy, market position, or competitive landscape.'},
        {'name': 'Organizational', 'description': 'Risks related to organizational structure, culture, or human resources.'},
    ]
    
    for category_data in categories:
        Category.objects.create(**category_data)


def reverse_func(apps, schema_editor):
    Category = apps.get_model('risks', 'Category')
    # Delete the default categories
    Category.objects.filter(name__in=['Technical', 'Financial', 'Operational', 'Legal', 'Strategic', 'Organizational']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_category'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_func),
    ]