# Generated by Django 5.1.7 on 2025-03-18 05:44

import django.db.models.deletion
from django.db import migrations, models

def migrate_category_data(apps, schema_editor):
    Risk = apps.get_model('risks', 'Risk')
    Category = apps.get_model('risks', 'Category')
    
    # Create a mapping of category names to category objects
    category_map = {category.name: category for category in Category.objects.all()}
    
    # Update each risk to use the appropriate Category object
    for risk in Risk.objects.all():
        old_category_value = risk.old_category
        if old_category_value in category_map:
            risk.category = category_map[old_category_value]
            risk.save(update_fields=['category'])
        else:
            # Use default category if no match
            risk.category = category_map.get('Operational')
            risk.save(update_fields=['category'])

class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='old_category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Financial', 'Financial'), ('Operational', 'Operational'), ('Legal', 'Legal')], default='Operational', max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='risks.category'),
        ),
        migrations.RunPython(migrate_category_data, migrations.RunPython.noop),
    ]
