# Generated by Django 5.1.7 on 2025-03-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_add_created_by_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='created_by',
        ),
    ]
