# Generated by Django 5.1.6 on 2025-05-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0009_riskresponse_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='likelihood_percentage',
            field=models.IntegerField(default=10, help_text='Probability of risk occurring (1-100%)'),
        ),
        migrations.AddField(
            model_name='risk',
            name='most_likely_cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Most probable cost impact if risk occurs', max_digits=12),
        ),
        migrations.AddField(
            model_name='risk',
            name='optimistic_cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Best-case cost impact if risk occurs', max_digits=12),
        ),
        migrations.AddField(
            model_name='risk',
            name='pessimistic_cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Worst-case cost impact if risk occurs', max_digits=12),
        ),
    ]
